# Build settings
theme: minima
plugins:
  - jekyll-feed

title: Research Project FANZinE
shorttitle: Home # Text for Link to home on all pages
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Football as the basis for social cohesion in Europe (FANZinE) is a research project based at the University of Mainz, Germany. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "fanzine-research.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: eu_foot
github_username:  fanzine-research

show_excerpts: true

